In [21]:
import torch
import numpy as np

In [19]:
normal = torch.distributions.Normal(torch.randn(3,5,2),torch.rand(3,5,2))
torch.distributions.independent.Independent(normal,1).log_prob(torch.tensor([0.0,0.0]))
normal.log_prob(torch.tensor([0.0,0.0]))

tensor([[[-1.2479e+00, -6.7383e+04],
         [-2.6813e+00, -1.2371e+01],
         [-1.8561e-01, -9.0327e-01],
         [-2.4457e-01, -1.0101e+01],
         [-1.4895e+00, -4.1650e-01]],

        [[-2.0416e+00, -5.2498e+01],
         [-2.1067e-01, -3.2064e+01],
         [-9.1517e-01, -1.6738e+00],
         [-1.3114e+00, -8.0311e-01],
         [-4.5645e-01, -1.2694e+00]],

        [[-9.2305e-01, -1.6899e+00],
         [-1.6812e+00, -7.6935e-01],
         [-9.0025e-02, -1.6176e+00],
         [-1.4707e+03,  1.5584e+00],
         [-8.5955e+00, -1.5195e+00]]])

In [168]:
def sample_sigma_matrix():
    t1,t2,t3 = [int(np.random.uniform(-100,100)) for _ in range(3)]
    mat = np.array([[t1,0],[t2,t3]]) 
    return torch.tensor(np.matmul(mat,mat.T) + 0.01*np.eye(2), dtype=torch.float32)

sigmas = [sample_sigma_matrix(), 
          sample_sigma_matrix(),
          sample_sigma_matrix()]
# sigmas = torch.block_diag(*sigmas)
sigmas = torch.stack(sigmas)
sigmas = torch.stack([sigmas]*10)


normal = torch.distributions.MultivariateNormal(loc=torch.randn((10,3,2),dtype=torch.float32), 
                                                covariance_matrix=sigmas)
normal.log_prob(torch.zeros(2)).shape

torch.Size([10, 3])

In [ ]:
num_mixtures = 2
num_vars = 3
batch_size = 100
output_size = num_vars + num_vars*(num_vars+1)/2 + 1

output = [torch.rand(batch_size, output_size)]*num_mixtures



In [95]:
import math

d_model = 10
max_len = 100

position = torch.arange(max_len).unsqueeze(1)
div_term = torch.exp(torch.arange(0, d_model, 2) * (-math.log(10000.0) / d_model))
pe = torch.zeros(1, max_len, d_model)
pe[0, :, 0::2] = torch.sin(position * div_term)
pe[0, :, 1::2] = torch.cos(position * div_term)

pe.shape

x = torch.rand(1000, 90, 10)
(x+ pe[0, :90]).shape


torch.Size([1000, 90, 10])

In [169]:
batch_size = 1000
num_mix = 2
x = torch.rand(batch_size,num_mix,10,requires_grad=True)

mat_size = [int(math.sqrt(x.shape[-1]*2))]*2
mat = torch.zeros(batch_size, num_mix, *mat_size)
idx1, idx2 = torch.tril_indices(*mat_size)
mat[:,:,idx1,idx2] = x
# # # idx = [[j for j in range(1,i+1)] for i in range(1,4+1)]
mat.cuda()
mat.to(mat.device)
mat.matmul(mat.transpose(-2,-1))

tensor([[[[7.4539e-01, 3.5683e-01, 5.7106e-01, 3.2024e-01],
          [3.5683e-01, 3.7715e-01, 4.8918e-01, 2.3793e-01],
          [5.7106e-01, 4.8918e-01, 1.2830e+00, 7.6329e-01],
          [3.2024e-01, 2.3793e-01, 7.6329e-01, 9.7264e-01]],

         [[7.5084e-01, 2.3949e-01, 4.6004e-02, 8.5122e-01],
          [2.3949e-01, 1.0196e+00, 5.0611e-01, 4.5203e-01],
          [4.6004e-02, 5.0611e-01, 5.2918e-01, 1.6880e-01],
          [8.5122e-01, 4.5203e-01, 1.6880e-01, 1.0864e+00]]],


        [[[4.5210e-02, 1.9557e-01, 1.5964e-01, 1.5653e-01],
          [1.9557e-01, 1.6113e+00, 1.4835e+00, 8.9017e-01],
          [1.5964e-01, 1.4835e+00, 1.6993e+00, 1.3236e+00],
          [1.5653e-01, 8.9017e-01, 1.3236e+00, 2.1124e+00]],

         [[9.8831e-02, 2.7721e-01, 5.0725e-02, 5.0823e-02],
          [2.7721e-01, 9.5176e-01, 4.4258e-01, 1.4724e-01],
          [5.0725e-02, 4.4258e-01, 5.9737e-01, 2.5958e-01],
          [5.0823e-02, 1.4724e-01, 2.5958e-01, 1.1063e+00]]],


        [[[8.1448e-03, 4.483

In [173]:
x = torch.arange(4).reshape(2,2)
print(x)
x.reshape(-1,4)

tensor([[0, 1],
        [2, 3]])


tensor([[0, 1, 2, 3]])